// import img from '../../assets/images/'
export const objOne = {
    id: 'info',
    link: '/about',
    fade: true,
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Nsexpress digitals',
    headline: 'Premium designs with zero effort',
    desc: "Exquisite designs of world-class standard that helps you send your brand's message effectively",
    buttonLabel: 'Get started',
    imgStart: false,
    img: '/svgs/svg-2.svg',
    alt: '',
    dark: true,
    primary: true,
    darkText: false
};
export const objTwo = {
    id: 'discover',
    link: '/',
    fade: false,
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Why Nsexpress digitals?',
    headline: 'Digital solutions at a click',
    desc: "Creating well-defined digital methods to attract customers",
    buttonLabel: 'Read more',
    imgStart: true,
    img: '/svgs/svg-1.svg',
    alt: '',
    dark: false,
    primary: true,
    darkText: false
}
export const objThree = {
    id: 'signup',
    link: '/trainings',
    fade: false,
    lightBg: false,
    lightText: false,
    lightTextDesc: false,
    topLine: 'It Training & Consultancy',
    headline: 'Consultancy with a single click',
    desc: "Making you self-reliant in tech through premium mentorship",
    buttonLabel: 'Start Now',
    imgStart: false,
    img: '/svgs/svg-3.svg',
    alt: 'Paper',
    dark: false,
    primary: true,
    darkText: true 
}